<sam type="rule" name="page3.drl">
package lifeengine.dashboard 
rule "I like crisps tuesdays"
when
	UserCommand(message.equals("crispst")) from entry-point "Remote Users"
then
	System.out.println("Crisps are tgood");
end

rule "I like cheese everyday but not stilton everyday"
when
	$uc : UserCommand(message == "stilton") from entry-point "Remote Users"
then
	System.out.println($uc.getMessage() + " is good");
end


</sam>
