<sam type="sparql" name="ideas.sparql">

PREFIX : &lt;http://samsquire.com/&gt; 
PREFIX owl: &lt;http://www.w3.org/2002/07/owl#&gt; 
PREFIX rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt; 
PREFIX xml: &lt;http://www.w3.org/XML/1998/namespace&gt; 
PREFIX xsd: &lt;http://www.w3.org/2001/XMLSchema#&gt; 
PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt; 
PREFIX samsquire: &lt;http://samsquire.com/&gt; 
BASE &lt;http://samsquire.com/&gt; 

INSERT DATA {
:Idea a owl:Class .
:IdeaStatus a owl:Class.
:IdeaProgress a owl:ObjectProperty.

:SiteTag a owl:AnnotationProperty.

:NoKnownImplementations a owl:Class;
        rdfs:subClassOf :IdeaStatus.
        
:AttemptedImplementation a owl:Class;
        rdfs:subClassOf :IdeaStatus.

:EncryptionServer a owl:Class;
		a :Idea;
	 :SiteTag "EncryptionServer".

:OpenEmailMetadata a owl:Class; a :Idea; :SiteTag "OpenEmailMetadata".
:Dashboard a owl:Class; rdfs:subClassOf :Idea; :SiteTag "Dashboard".
:LifeEngineDashboard a :Dashboard; :SiteTag "LifeEngineDashboard".
:MagazineDashboard a :Dashboard; :SiteTag "MagazineDashboard".

}
</sam>
